### PR TITLE
Make Suspenders abort when something goes wrong

### LINKED ISSUE #1073: Make suspenders command smarter regarding the Ruby version
If I run Suspenders with a Ruby version other than the one declared in `Gemfile`, I'm still able to generate my application but I get the following message over and over:

> Your Ruby version is X.X.X, but your Gemfile specified 2.6.6

 Here's some sample output:

```
Your Ruby version is 2.7.2, but your Gemfile specified 2.6.6
    generate  suspenders:advisories
       rails  generate suspenders:advisories
Your Ruby version is 2.7.2, but your Gemfile specified 2.6.6
    generate  suspenders:preloader
       rails  generate suspenders:preloader
Your Ruby version is 2.7.2, but your Gemfile specified 2.6.6
    generate  suspenders:staging:pull_requests
       rails  generate suspenders:staging:pull_requests
Your Ruby version is 2.7.2, but your Gemfile specified 2.6.6
    generate  suspenders:production:single_redirect
       rails  generate suspenders:production:single_redirect
Your Ruby version is 2.7.2, but your Gemfile specified 2.6.6
    generate  suspenders:production:compression
       rails  generate suspenders:production:compression
Your Ruby version is 2.7.2, but your Gemfile specified 2.6.6
    generate  suspenders:production:force_tls
```

There are some options to deal with this problem. The following ones crossed my mind:

1. Declare the minimum and maximum Ruby versions, and configure `Gemfile` with whatever version the user is using. If the user's version is less than the minimum or the maximum, fail before running anything.
2. Fail if the user's Ruby version is different than `Suspenders::RUBY_VERSION`

### PR DESCRIPTION
**Pull request by thiagoa**
Closes [#1080](https://github.com/thoughtbot/suspenders/issues/1080)

This task is part of our "Rescue" board: https://github.com/thoughtbot/suspenders/projects/1

## What changed?

`bin/suspenders` is now halting on error. Not halting on error was a huge source of confusion for Suspenders users. Some examples of issues we are resolving here:

- If using the wrong Ruby version, Suspenders will fail loudly. Currently, Suspenders is limited to a single Ruby version (we'll make the Ruby version flexible in another PR.) Example:

```
      create  storage/.keep
      create  tmp/storage
      create  tmp/storage/.keep
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_6_1.rb
       force  Gemfile
         run  bundle install
Your Ruby version is 2.7.5, but your Gemfile specified 2.7.4
```

No more output. The user will instantly know something is wrong and will attempt to fix the error.

- If Postgres is not running, Suspenders will fail when trying to create the database
- If a generator fails because of some unmet requirement, Suspenders will halt as well (recall that every individual generator runs within a subprocess.)

## Changelog

- Override thor's `exit_on_failure?` to `true` on `AppGenerator`. `AppGenerator` is the class that extends `Rails::Generators::AppGenerator` and runs our own version of `rails new` through `bin/suspenders`.
- Override thor's `exit_on_failure?` to `true` on `Suspenders::Generators::Base` (the base class of our individual generators.)
- Make `Rails::Generators::AppGenerator#bundle_command` fail on error. Unfortunately, it is not hooked up to thor's default error handling mechanism, so it won't leverage Thor's `exit_on_failure` setting.
- Override the default value of `skip_spring` to `true`. Rails will still try to generate spring binstubs when finishing up the application, which would make `bin/suspenders` fail given our newly introduced `exit_on_failure` setting.
- Avoid the `spring stop` command from halting `bin/suspenders` when `spring` is not installed or when it calls a binstub that can't find the real `spring`.
- Add unit tests for the new settings. `exit_on_failure` is a `:nodoc:` in Thor, and it's unfortunate they don't provide an official setting for that. If it ever breaks, we'll need to know.
- Don't run the stylesheets generator when `--api` is set. That avoids the stylesheet generator (and thus `bin/suspenders`) from failing with our new settings.
- Rename `DEBUG` => `SHOW_DEBUG` because `DEBUG` is already taken by Ruby and prints out too many symbols.

### CODE REVIEW

File: lib/suspenders/generators/app_generator.rb [hunk 1]
```diff
@@ -138,18 +143,16 @@ def remove_routes_comment_lines
...
 
     def generate_default
-      run("spring stop > /dev/null 2>&1")
+      run("spring stop > /dev/null 2>&1 || true")
       generate("suspenders:runner")
       generate("suspenders:profiler")
       generate("suspenders:json")
       generate("suspenders:static")
-      generate("suspenders:stylesheet_base")
+      generate("suspenders:stylesheet_base") unless options[:api]
```
Comment (thiagoa) [inline lib/suspenders/generators/app_generator.rb:151]: This prevents `api_spec.rb` from failing because it tries to run `yarn` but there's no such command in API mode. I'm sure there are other generators we'll want to skip in that case, and we'll probably want to address them in a future PR.

File: spec/support/feature_test_helpers.rb [hunk 2]
```diff
@@ -158,7 +177,7 @@ def run_in_project
   end
 
   def debug(output)
-    if ENV["DEBUG"]
```
Comment (thiagoa) [inline spec/support/feature_test_helpers.rb:161]: It looks like `DEBUG` is already taken by Ruby and it outputs a ton of garbage.

**Review by mike-burns — APPROVED** [review]
Nice! Thank you for doing this.
